version: '3.9'

services:
  backend:
    container_name: api
    image: api
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
  db:
    container_name: dbs
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
